### PR TITLE
SSToolkit no longer required

### PR DESCRIPTION
**Pull request by markrickert**
Removed SSToolkit dependency. Fixes issue #5.

### CODE REVIEW

**Comment by soffes** [comment]
Trying to decide what to do here. I have a little app that I'll be working on soon that will use this. I'll most likely be using more of SSToolkit in SSMessagesViewController, so the approach of just copying pieces won't really scale. Also, it makes it more annoying to add SSMessagesViewController to your project if you already have SSToolkit in your project.

For now, I think if people don't want the SSToolkit dependency, they can just use your fork. Thanks for your work splitting it out. I definitely appreciate the help!

**Comment by markrickert** [comment]
No worries... I'm getting ready to do a pretty big app where I'm going to _attempt_ to add things like timestamp views and name indicators for multiple people in the chat... kind of like what Whatsapp does.

**Comment by soffes** [comment]
Nice. Ya'll be adding a subtitle for date, read, etc. avatars, draw the bubbles so you can set a UIColor instead of having lots of images, autoresizing textfield, better animations, etc. I'd love any help :)

**Comment by markrickert** [comment]
Well, I'm using it in a project and didn't need the other toolkit classes, so i figured i'd just remove yet ANOTHER submodule from my repos, lol.

I'm also planning on making a few improvements for detecting if the view is inside a UITabBarController. In my version, i have just hardcoded the offset to account for it, but I may just see what I can do to make it go automatically so it'll be more future-proof.

I'll help to the extend that I can... I'm by no means a wizard at this stuff, but people pay me to do it so that says something, i guess, lol.

**Comment by markrickert** [comment]
Hey Sam, Just wanted to update you on a little work I did today. I added a "detail view" to the bubble cells with a customizable text color and backgrounds.

It defaults to not display if the text isn't set and then if it is, defaults the background to white and text to black. It also works for both SSMessageStyles!

Check out the commit here: https://github.com/markrickert/ssmessagesviewcontroller/commit/c15a5667a6d31af6938d8c853bcfcd60cbc1b716

Here's what it looks like with the orange of my application:

screencap

**Comment by markrickert** [comment]
And here's my subclass implementation:

enjoy!

(and let me know if this stuff is useful to you at ALL, lol)

``` objective-c
- (SSMessageStyle)messageStyleForRowAtIndexPath:(NSIndexPath *)indexPath
{
    Message *thisMessage = [_thisConversation objectAtIndex:indexPath.row];

  if (thisMessage.isYou)
        return SSMessageStyleRight;
  else 
    return SSMessageStyleLeft;
}

- (NSString *)textForRowAtIndexPath:(NSIndexPath *)indexPath
{
    Message *thisMessage = [_thisConversation objectAtIndex:indexPath.row];
    return thisMessage.body;
}

- (NSString *)detailTextForRowAtIndexPath:(NSIndexPath *)indexPath
{
    if([self messageStyleForRowAtIndexPath:indexPath] == SSMessageStyleRight)
        return nil;

    Message *thisMessage = [_thisConversation objectAtIndex:indexPath.row];
    return thisMessage.user_name;
}

- (UIColor *)detailTextColorForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return [UIColor whiteColor];
}

- (UIColor *)detailBackgroundColorForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return kMyUglyOrangeColor; // <- this is a UIColor constant     
}

```

**Pull request closed without merging**
